artefacts_root: artefacts

data_ingestion:
  root_dir: artefacts/data_ingestion
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/samsumdata.zip
  local_data_files: artefacts/data_ingestion/samsumdata.zip
  unzip_dir: artefacts/data_ingestion

data_validation:
  root_dir: artefacts/data_validation
  STATUS_FILE: artefacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train", "test", "validation"]

data_tranformation:
  root_dir: artefacts/data_transformation
  data_path: artefacts/data_ingestion/samsum_dataset
  tokenizer_name: google/pegasus-cnn_dailymail

model_trainer:
  root_dir: artefacts/model_trainer
  data_path: artefacts/data_transformation/samsum_dataset
  model_ckpt: google/pegasus-cnn_dailymail