artefacts_root: artefacts

data_ingestion:
  root_dir: artefacts/data_ingestion
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/samsumdata.zip
  local_data_files: artefacts/data_ingestion/samsumdata.zip
  unzip_dir: artefacts/data_ingestion